import {
  LayoutDashboard,
  Activity,
  Users,
  Stethoscope,
  Radio,
  Package,
  FolderTree,
  RefreshCw,
  ShieldCheck,
  ClipboardList,
  BarChart3,
  TrendingUp,
  Settings,
} from 'lucide-react';
import type { RoleNavigation } from '../types';

export const ADMIN_NAVIGATION: RoleNavigation = {
  role: 'ADMIN',
  portalName: 'Portal de Administración',
  portalRoot: '/admin',
  tagline: 'Gestión global del sistema, usuarios y monitoreo',
  sections: [
    {
      id: 'admin-dashboard',
      archetype: 'dashboard',
      label: 'Dashboard',
      icon: LayoutDashboard,
      items: [
        {
          id: 'admin-resumen',
          label: 'Resumen General',
          path: '/dashboard/resumen',
          icon: LayoutDashboard,
          component: 'DashboardCard',
          status: 'active',
        },
        {
          id: 'admin-salud-sistema',
          label: 'Salud del Sistema',
          path: '/dashboard/salud-sistema',
          icon: Activity,
          component: 'StatsWidget',
          status: 'active',
        },
      ],
    },
    {
      id: 'admin-core-modules',
      archetype: 'core-modules',
      label: 'Gestión Principal',
      icon: Users,
      items: [
        {
          id: 'admin-usuarios-roles',
          label: 'Usuarios y Roles',
          path: '/gestion-principal/usuarios-roles',
          icon: Users,
          component: 'ManagementPage',
          status: 'active',
        },
        {
          id: 'admin-brigadas-medicas',
          label: 'Brigadas Médicas',
          path: '/gestion-principal/brigadas-medicas',
          icon: Stethoscope,
          component: 'ManagementPage',
          status: 'active',
        },
        {
          id: 'admin-dispositivos-nodos',
          label: 'Dispositivos y Nodos',
          path: '/gestion-principal/dispositivos-nodos',
          icon: Radio,
          component: 'ManagementPage',
          status: 'active',
        },
        {
          id: 'admin-inventario-suministros',
          label: 'Inventario y Suministros',
          path: '/gestion-principal/inventario-suministros',
          icon: Package,
          component: 'ManagementPage',
          status: 'active',
        },
        {
          id: 'admin-catalogos-sistema',
          label: 'Catálogos del Sistema',
          path: '/gestion-principal/catalogos-sistema',
          icon: FolderTree,
          component: 'ListPage',
          status: 'active',
        },
      ],
    },
    {
      id: 'admin-operations',
      archetype: 'operations',
      label: 'Operaciones',
      icon: RefreshCw,
      items: [
        {
          id: 'admin-sincronizacion',
          label: 'Sincronización',
          path: '/operaciones/sincronizacion',
          icon: RefreshCw,
          component: 'ManagementPage',
          status: 'active',
        },
        {
          id: 'admin-seguridad',
          label: 'Seguridad',
          path: '/operaciones/seguridad',
          icon: ShieldCheck,
          component: 'SettingsPage',
          status: 'active',
        },
        {
          id: 'admin-auditoria',
          label: 'Auditoría',
          path: '/operaciones/auditoria',
          icon: ClipboardList,
          component: 'TableView',
          status: 'active',
        },
      ],
    },
    {
      id: 'admin-reports',
      archetype: 'reports',
      label: 'Reportes',
      icon: BarChart3,
      items: [
        {
          id: 'admin-reportes-operativos',
          label: 'Reportes Operativos',
          path: '/reportes/reportes-operativos',
          icon: BarChart3,
          component: 'TableView',
          status: 'active',
        },
        {
          id: 'admin-uso-sistema',
          label: 'Uso del Sistema',
          path: '/reportes/uso-sistema',
          icon: TrendingUp,
          component: 'StatsWidget',
          status: 'active',
        },
      ],
    },
    {
      id: 'admin-settings',
      archetype: 'settings',
      label: 'Configuración',
      icon: Settings,
      items: [
        {
          id: 'admin-parametros-generales',
          label: 'Parámetros Generales',
          path: '/configuracion/parametros-generales',
          icon: Settings,
          component: 'SettingsPage',
          status: 'active',
        },
      ],
    },
  ],
};
