import {
  LayoutDashboard,
  TrendingUp,
  Map,
  AlertTriangle,
  Siren,
  History,
  Network,
  MapPinned,
  Users,
  ClipboardList,
  FileBarChart,
  BarChart3,
  BrainCircuit,
  Settings,
  User,
  SlidersHorizontal,
} from 'lucide-react';
import type { RoleNavigation } from '../types';

export const AUTORIDAD_SALUD_NAVIGATION: RoleNavigation = {
  role: 'AUTORIDAD_SALUD',
  portalName: 'Portal de Autoridades de Salud',
  portalRoot: '/authority',
  tagline: 'Supervisión estratégica, indicadores y toma de decisiones',
  sections: [
    {
      id: 'authority-dashboard',
      archetype: 'dashboard',
      label: 'Dashboard Ejecutivo',
      icon: LayoutDashboard,
      items: [
        {
          id: 'authority-executive-dashboard',
          label: 'Dashboard Ejecutivo',
          path: '/dashboard',
          icon: LayoutDashboard,
          component: 'DashboardCard',
          status: 'active',
        },
        {
          id: 'authority-kpis',
          label: 'KPIs Estratégicos',
          path: '/dashboard/kpis',
          icon: TrendingUp,
          component: 'StatsWidget',
          status: 'active',
        },
      ],
    },
    {
      id: 'authority-core-modules',
      archetype: 'core-modules',
      label: 'Análisis y Monitoreo',
      icon: Map,
      items: [
        {
          id: 'authority-national-map',
          label: 'Mapa Nacional',
          path: '/national-map',
          icon: Map,
          component: 'MapView',
          status: 'active',
        },
        {
          id: 'authority-epidemiological',
          label: 'Brotes Epidemiológicos',
          path: '/epidemiological-outbreaks',
          icon: AlertTriangle,
          component: 'MapView',
          status: 'active',
          badgeKey: 'activeOutbreaks',
          children: [
            {
              id: 'authority-outbreaks-active',
              label: 'Brotes Activos',
              path: '/epidemiological-outbreaks/active',
              icon: Siren,
              component: 'ListPage',
              status: 'active',
            },
            {
              id: 'authority-outbreaks-history',
              label: 'Historial de Brotes',
              path: '/epidemiological-outbreaks/history',
              icon: History,
              component: 'TableView',
              status: 'active',
            },
          ],
        },
        {
          id: 'authority-coverage',
          label: 'Cobertura de Salud',
          path: '/coverage',
          icon: Network,
          component: 'DetailsPage',
          status: 'active',
          children: [
            {
              id: 'authority-coverage-regional',
              label: 'Cobertura Regional',
              path: '/coverage/regional',
              icon: MapPinned,
              component: 'MapView',
              status: 'active',
            },
            {
              id: 'authority-coverage-population',
              label: 'Cobertura Poblacional',
              path: '/coverage/population',
              icon: Users,
              component: 'StatsWidget',
              status: 'active',
            },
          ],
        },
        {
          id: 'authority-national-network',
          label: 'Red Nacional',
          path: '/national-network',
          icon: Network,
          component: 'MapView',
          status: 'active',
        },
      ],
    },
    {
      id: 'authority-operations',
      archetype: 'operations',
      label: 'Alertas y Auditoría',
      icon: Siren,
      items: [
        {
          id: 'authority-national-alerts',
          label: 'Alertas Nacionales',
          path: '/national-alerts',
          icon: Siren,
          component: 'ListPage',
          status: 'active',
          badgeKey: 'nationalAlerts',
        },
        {
          id: 'authority-audits',
          label: 'Auditorías',
          path: '/audits',
          icon: ClipboardList,
          component: 'TableView',
          status: 'active',
        },
      ],
    },
    {
      id: 'authority-reports',
      archetype: 'reports',
      label: 'Reportes y Estadísticas',
      icon: FileBarChart,
      items: [
        {
          id: 'authority-reports-national',
          label: 'Reportes Nacionales',
          path: '/reports/national',
          icon: FileBarChart,
          component: 'TableView',
          status: 'active',
        },
        {
          id: 'authority-statistics',
          label: 'Estadísticas',
          path: '/statistics',
          icon: BarChart3,
          component: 'StatsWidget',
          status: 'active',
        },
        {
          id: 'authority-reports-advanced',
          label: 'Estadísticas Avanzadas (IA)',
          path: '/statistics/advanced',
          icon: BrainCircuit,
          component: 'StatsWidget',
          status: 'planned',
        },
      ],
    },
    {
      id: 'authority-settings',
      archetype: 'settings',
      label: 'Configuración',
      icon: Settings,
      items: [
        {
          id: 'authority-settings-profile',
          label: 'Perfil',
          path: '/settings/profile',
          icon: User,
          component: 'SettingsPage',
          status: 'active',
        },
        {
          id: 'authority-settings-alert-thresholds',
          label: 'Umbrales de Alerta',
          path: '/settings/alert-thresholds',
          icon: SlidersHorizontal,
          component: 'SettingsPage',
          status: 'active',
        },
      ],
    },
  ],
};