// =========================================================================
// ARCHIVO: apps/api/prisma/seed.ts
// DESCRIPCIÓN: Sembrado maestro para MedicOS (103 Establecimientos Oficiales,
//              IAM, Dispositivos, Brigadas, Pacientes, Consultas y Auditoría).
// =========================================================================

import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';
import pg from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import {
  PrismaClient,
  Prisma,
  Role,
  Sex,
  BloodType,
  BrigadeStatus,
  ConsultationStatus,
  UserStatus,
  DeviceStatus,
  SyncOperation,
  QueueStatus,
  SessionStatus,
  EstablishmentType,
  EstablishmentLevel,
  EstablishmentOperator,
  EstablishmentStatus,
  SyncStatus,
} from '@prisma/client';
import bcrypt from 'bcryptjs';

// Cargar variables de entorno del paquete API
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.resolve(__dirname, '../.env') });

const connectionString = process.env.DATABASE_URL;

if (!connectionString) {
  throw new Error('DATABASE_URL no se encuentra definida en el archivo .env');
}

const pool = new pg.Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const SYSTEM_DEVICE_ID = 'SYSTEM_OFFICIAL_MINSAL_ISSS_2026';

// Interfaces tipadas para datos de sembrado
interface EstablishmentSeedRecord {
  code: string;
  name: string;
  type: EstablishmentType;
  level: EstablishmentLevel;
  operator: EstablishmentOperator;
  department: string;
  municipality: string;
  address: string;
  phone: string | null;
  emergencyPhone: string | null;
  hasEmergency: boolean;
  latitude: number | null;
  longitude: number | null;
  specialties: string[];
}

interface PacienteSeedData {
  userId: string;
  firstName: string;
  lastName: string;
  dui: string;
  dob: Date;
  sex: Sex;
  phone: string;
  address: string;
  bloodType: BloodType;
  familyHistory: string;
  createdAt: Date;
}

type PatientWithClinicalRecord = Prisma.PatientGetPayload<{
  include: { clinicalRecord: true };
}>;

// =========================================================================
// 1. CATÁLOGO OFICIAL DE HOSPITALES (42)
// =========================================================================
const verifiedNationalHospitals: EstablishmentSeedRecord[] = [
  // MINSAL (31)
  {
    code: 'MINSAL-HN-001',
    name: 'Hospital Nacional Rosales',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.SPECIALIZED,
    operator: EstablishmentOperator.MINSAL,
    department: 'San Salvador',
    municipality: 'San Salvador',
    address: 'Final 25 Avenida Norte y Calle Arce, San Salvador',
    phone: '+503 2594-3000',
    emergencyPhone: '+503 2231-9200',
    hasEmergency: true,
    latitude: 13.7008703,
    longitude: -89.2042204,
    specialties: ['Medicina Interna', 'Cirugía General', 'Especialidades Quirúrgicas'],
  },
  {
    code: 'MINSAL-HN-002',
    name: 'Hospital Nacional Especializado de Niños "Benjamín Bloom"',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.SPECIALIZED,
    operator: EstablishmentOperator.MINSAL,
    department: 'San Salvador',
    municipality: 'San Salvador',
    address: 'Final 25 Avenida Norte, San Salvador',
    phone: '+503 2133-3100',
    emergencyPhone: '+503 2225-4114',
    hasEmergency: true,
    latitude: 13.7143739,
    longitude: -89.2039403,
    specialties: ['Pediatría Integral', 'Cirugía Pediátrica', 'Subespecialidades Pediátricas'],
  },
  {
    code: 'MINSAL-HN-003',
    name: 'Hospital Nacional de la Mujer "Dra. María Isabel Rodríguez"',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.SPECIALIZED,
    operator: EstablishmentOperator.MINSAL,
    department: 'San Salvador',
    municipality: 'San Salvador',
    address: 'Final 25 Avenida Sur y Calle Francisco Menéndez, Barrio Santa Anita, San Salvador',
    phone: '+503 2206-6200',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.6906741,
    longitude: -89.2043962,
    specialties: ['Ginecología', 'Obstetricia', 'Perinatología', 'Neonatología'],
  },
  {
    code: 'MINSAL-HN-004',
    name: 'Hospital Nacional El Salvador',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.SPECIALIZED,
    operator: EstablishmentOperator.MINSAL,
    department: 'San Salvador',
    municipality: 'San Salvador',
    address: 'Avenida de La Revolución No. 222, Colonia San Benito, San Salvador',
    phone: '+503 2594-2100',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.6884694,
    longitude: -89.2357836,
    specialties: ['Cuidados Críticos', 'Atención Especializada', 'Telemedicina'],
  },
  {
    code: 'MINSAL-HN-005',
    name: 'Hospital Nacional General de Neumología y Medicina Familiar "Dr. José Antonio Saldaña"',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.SPECIALIZED,
    operator: EstablishmentOperator.MINSAL,
    department: 'San Salvador',
    municipality: 'Panchimalco',
    address: 'Km. 8 ½, Carretera a Los Planes de Renderos, San Salvador',
    phone: '+503 2594-5700',
    emergencyPhone: '+503 2201-2100',
    hasEmergency: true,
    latitude: 13.6472109,
    longitude: -89.1945984,
    specialties: ['Neumología', 'Medicina Familiar', 'Patologías Respiratorias'],
  },
  {
    code: 'MINSAL-HN-006',
    name: 'Hospital Nacional General y de Psiquiatría "Dr. José Molina Martínez"',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.SPECIALIZED,
    operator: EstablishmentOperator.MINSAL,
    department: 'San Salvador',
    municipality: 'Soyapango',
    address: 'Calle La Fuente, Cantón Venecia, Soyapango, San Salvador',
    phone: '+503 2327-0200',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.7142761,
    longitude: -89.138315,
    specialties: ['Salud Mental', 'Psiquiatría', 'Rehabilitación Psicosocial'],
  },
  {
    code: 'MINSAL-HN-007',
    name: 'Hospital Nacional General "Dr. Juan José Fernández", Zacamil',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.MINSAL,
    department: 'San Salvador',
    municipality: 'Mejicanos',
    address: 'Urbanización José Simeón Cañas, Colonia Zacamil, San Salvador',
    phone: '+503 2594-5000',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.7326,
    longitude: -89.2133,
    specialties: ['Cirugía General', 'Maternidad', 'Pediatría', 'Medicina Interna'],
  },
  {
    code: 'MINSAL-HN-008',
    name: 'Hospital Nacional General "Enf. Angélica Vidal de Najarro", San Bartolo',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.MINSAL,
    department: 'San Salvador',
    municipality: 'Ilopango',
    address: 'Final Calle Francisco Menéndez, contiguo a Zona Franca San Bartolo, Ilopango, San Salvador',
    phone: '+503 2201-3100',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.7043121,
    longitude: -89.1060703,
    specialties: ['Medicina Interna', 'Cirugía General', 'Pediatría', 'Ginecología'],
  },
  {
    code: 'MINSAL-HN-009',
    name: 'Hospital Nacional Regional "San Juan de Dios", Santa Ana',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.REGIONAL,
    operator: EstablishmentOperator.MINSAL,
    department: 'Santa Ana',
    municipality: 'Santa Ana',
    address: 'Final 13 Avenida Sur No. 1, Santa Ana',
    phone: '+503 2891-1500',
    emergencyPhone: '+503 2435-9500',
    hasEmergency: true,
    latitude: 13.9918759,
    longitude: -89.5512748,
    specialties: ['Cirugía General', 'Cuidados Intensivos', 'Medicina Interna', 'Pediatría', 'Ginecología'],
  },
  {
    code: 'MINSAL-HN-010',
    name: 'Hospital Nacional General "Dr. Jorge Mazzini Villacorta"',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.MINSAL,
    department: 'Sonsonate',
    municipality: 'Sonsonate',
    address: 'Calle Alberto Masferrer Poniente #3-1, Sonsonate',
    phone: '+503 2891-6500',
    emergencyPhone: '+503 2451-0200',
    hasEmergency: true,
    latitude: 13.7228276,
    longitude: -89.7292116,
    specialties: ['Urgencias', 'Traumatología', 'Maternidad', 'Pediatría'],
  },
  {
    code: 'MINSAL-HN-011',
    name: 'Hospital Nacional General "Dr. Francisco Menéndez"',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.MINSAL,
    department: 'Ahuachapán',
    municipality: 'Ahuachapán',
    address: 'Calle Zacamil, Cantón Ashapuco, Ahuachapán',
    phone: '+503 2891-1400',
    emergencyPhone: '+503 2445-6800',
    hasEmergency: true,
    latitude: 13.9292485,
    longitude: -89.8464141,
    specialties: ['Medicina General', 'Cirugía Básica', 'Pediatría', 'Gineco-Obstetricia'],
  },
  {
    code: 'MINSAL-HN-012',
    name: 'Hospital Nacional General "Dr. Arturo Morales", Metapán',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.MINSAL,
    department: 'Santa Ana',
    municipality: 'Metapán',
    address: 'Carretera Internacional Km. 112, Metapán, Santa Ana',
    phone: '+503 2891-1600',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 14.3248378,
    longitude: -89.4431944,
    specialties: ['Medicina General', 'Cirugía Básica', 'Pediatría'],
  },
  {
    code: 'MINSAL-HN-013',
    name: 'Hospital Nacional General de Chalchuapa',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.MINSAL,
    department: 'Santa Ana',
    municipality: 'Chalchuapa',
    address: 'Final Avenida 2 de Abril Norte, Chalchuapa, Santa Ana',
    phone: '+503 2891-4500',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.986111,
    longitude: -89.681111,
    specialties: ['Cirugía General', 'Atención Materno-Infantil', 'Urgencias'],
  },
  {
    code: 'MINSAL-HN-014',
    name: 'Hospital Nacional General "San Rafael", Santa Tecla',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.REGIONAL,
    operator: EstablishmentOperator.MINSAL,
    department: 'La Libertad',
    municipality: 'Santa Tecla',
    address: '4ª Calle Oriente No. 9-2, Santa Tecla, La Libertad',
    phone: '+503 2594-4000',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.671168,
    longitude: -89.2782914,
    specialties: ['Urgencias 24/7', 'Trauma', 'Cirugía Laparoscópica', 'Cuidados Críticos'],
  },
  {
    code: 'MINSAL-HN-015',
    name: 'Hospital Nacional General "Dr. Luis Edmundo Vásquez"',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.MINSAL,
    department: 'Chalatenango',
    municipality: 'Chalatenango',
    address: 'Barrio San Antonio, Chalatenango',
    phone: '+503 2991-0000',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 14.0385126,
    longitude: -88.9362493,
    specialties: ['Atención Hospitalaria Integral', 'Ginecología', 'Urgencias'],
  },
  {
    code: 'MINSAL-HN-016',
    name: 'Hospital Nacional General de Nueva Concepción',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.MINSAL,
    department: 'Chalatenango',
    municipality: 'Nueva Concepción',
    address: '9ª Calle Oriente, Barrio Rosario, Nueva Concepción, Chalatenango',
    phone: '+503 2991-0500',
    emergencyPhone: '+503 2347-5200',
    hasEmergency: true,
    latitude: 14.1313917,
    longitude: -89.2883944,
    specialties: ['Maternidad', 'Urgencias Comunitarias', 'Cirugía Básica'],
  },
  {
    code: 'MINSAL-HN-017',
    name: 'Hospital Nacional "Nuestra Señora de Fátima" de Cojutepeque',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.MINSAL,
    department: 'Cuscatlán',
    municipality: 'Cojutepeque',
    address: 'Barrio El Calvario, Km. 33 Antigua Carretera Panamericana, Cojutepeque, Cuscatlán',
    phone: '+503 2991-2200',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.722222,
    longitude: -88.932222,
    specialties: ['Emergencias', 'Pediatría', 'Cirugía General'],
  },
  {
    code: 'MINSAL-HN-018',
    name: 'Hospital Nacional General de Suchitoto',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.MINSAL,
    department: 'Cuscatlán',
    municipality: 'Suchitoto',
    address: 'Avenida José María Peña Fernández, Barrio El Calvario, Suchitoto, Cuscatlán',
    phone: '+503 2347-4700',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.9338102,
    longitude: -89.0288622,
    specialties: ['Medicina Familiar', 'Urgencias', 'Parto de Bajo Riesgo'],
  },
  {
    code: 'MINSAL-HN-019',
    name: 'Hospital Nacional General "Santa Teresa", Zacatecoluca',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.REGIONAL,
    operator: EstablishmentOperator.MINSAL,
    department: 'La Paz',
    municipality: 'Zacatecoluca',
    address: 'Final Avenida Juan Manuel Rodríguez, Calle al Volcán, Zacatecoluca, La Paz',
    phone: '+503 2347-1200',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.5172168,
    longitude: -88.8680208,
    specialties: ['Medicina Interna', 'Cirugía General', 'Pediatría', 'Obstetricia'],
  },
  {
    code: 'MINSAL-HN-020',
    name: 'Hospital Nacional General "Santa Gertrudis"',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.REGIONAL,
    operator: EstablishmentOperator.MINSAL,
    department: 'San Vicente',
    municipality: 'San Vicente',
    address: '2ª Avenida Sur No. 23, San Vicente',
    phone: '+503 2393-9500',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.6408928,
    longitude: -88.7837273,
    specialties: ['Cirugía', 'Medicina Interna', 'Pediatría', 'Urgencias 24 Horas'],
  },
  {
    code: 'MINSAL-HN-021',
    name: 'Hospital Nacional "San Jerónimo Emiliani" de Sensuntepeque',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.MINSAL,
    department: 'Cabañas',
    municipality: 'Sensuntepeque',
    address: '10ª Avenida Sur No. 1, Santa Bárbara, Sensuntepeque, Cabañas',
    phone: '+503 2361-0700',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.8751429,
    longitude: -88.622188,
    specialties: ['Urgencias 24/7', 'Atención Hospitalaria General', 'Pediatría'],
  },
  {
    code: 'MINSAL-HN-022',
    name: 'Hospital Nacional General "Dr. José Luís Saca", Ilobasco',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.MINSAL,
    department: 'Cabañas',
    municipality: 'Ilobasco',
    address: 'Final 4ª Calle Poniente, Barrio El Calvario, Ilobasco, Cabañas',
    phone: '+503 2347-5000',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.8391989,
    longitude: -88.8587581,
    specialties: ['Cirugía de Corta Estancia', 'Pediatría', 'Maternidad'],
  },
  {
    code: 'MINSAL-HN-023',
    name: 'Hospital Nacional General "San Pedro", Usulután',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.MINSAL,
    department: 'Usulután',
    municipality: 'Usulután',
    address: 'Final Calle Federico Penado, salida a San Salvador, Usulután',
    phone: '+503 2792-0000',
    emergencyPhone: '+503 2633-8800',
    hasEmergency: true,
    latitude: 13.3431402,
    longitude: -88.4498295,
    specialties: ['Medicina Interna', 'Cirugía General', 'Ginecología', 'Emergencias'],
  },
  {
    code: 'MINSAL-HN-024',
    name: 'Hospital Nacional de Jiquilisco',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.MINSAL,
    department: 'Usulután',
    municipality: 'Jiquilisco',
    address: '1ª Avenida Sur, Calle a Puerto Avalos, Cantón Roquinete, Jiquilisco, Usulután',
    phone: '+503 2684-3300',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.3189874,
    longitude: -88.571923,
    specialties: ['Medicina General', 'Pediatría', 'Maternidad'],
  },
  {
    code: 'MINSAL-HN-025',
    name: 'Hospital Nacional General "Dr. Jorge Arturo Mena", Santiago de María',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.MINSAL,
    department: 'Usulután',
    municipality: 'Santiago de María',
    address: '3ª Calle Poniente No. 15, Barrio Concepción, Santiago de María, Usulután',
    phone: '+503 2792-1000',
    emergencyPhone: '+503 2663-1606',
    hasEmergency: true,
    latitude: 13.4848701,
    longitude: -88.4685129,
    specialties: ['Atención Hospitalaria Secundaria', 'Pediatría', 'Obstetricia'],
  },
  {
    code: 'MINSAL-HN-026',
    name: 'Hospital Nacional Regional "San Juan de Dios", San Miguel',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.REGIONAL,
    operator: EstablishmentOperator.MINSAL,
    department: 'San Miguel',
    municipality: 'San Miguel',
    address: 'Final 11 Calle Poniente y 23 Avenida Sur, Colonia Ciudad Jardín, San Miguel',
    phone: '+503 2792-3000',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.4740703,
    longitude: -88.1909257,
    specialties: ['Cirugía General', 'Medicina Interna', 'Cuidados Intensivos', 'Cardiología'],
  },
  {
    code: 'MINSAL-HN-027',
    name: 'Hospital Nacional General de Nueva Guadalupe',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.MINSAL,
    department: 'San Miguel',
    municipality: 'Nueva Guadalupe',
    address: 'Barrio San Luis, Final Avenida Principal, Nueva Guadalupe, San Miguel',
    phone: '+503 2645-2200',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.5377068,
    longitude: -88.3491298,
    specialties: ['Medicina General', 'Pediatría', 'Atención de Emergencias'],
  },
  {
    code: 'MINSAL-HN-028',
    name: 'Hospital Nacional General "Monseñor Oscar Arnulfo Romero y Galdámez", Ciudad Barrios',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.MINSAL,
    department: 'San Miguel',
    municipality: 'Ciudad Barrios',
    address: '6ª Avenida Norte, Barrio Roma, Ciudad Barrios, San Miguel',
    phone: '+503 2792-2200',
    emergencyPhone: '+503 2684-1500',
    hasEmergency: true,
    latitude: 13.7667666,
    longitude: -88.2680037,
    specialties: ['Medicina General', 'Pediatría', 'Emergencias'],
  },
  {
    code: 'MINSAL-HN-029',
    name: 'Hospital Nacional General "Dr. Héctor Antonio Hernández Flores", San Francisco Gotera',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.MINSAL,
    department: 'Morazán',
    municipality: 'San Francisco Gotera',
    address: 'Final Avenida Thompson Norte, Barrio La Cruz, San Francisco Gotera, Morazán',
    phone: '+503 2645-7100',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.6950674,
    longitude: -88.102132,
    specialties: ['Servicios Hospitalarios Básicos', 'Maternidad', 'Cirugía Básica'],
  },
  {
    code: 'MINSAL-HN-030',
    name: 'Hospital Nacional General de La Unión',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.MINSAL,
    department: 'La Unión',
    municipality: 'Conchagua',
    address: 'Kilómetro 180, Carretera Panamericana, Cantón Huisquil, Conchagua, La Unión',
    phone: '+503 2792-5000',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.3499923,
    longitude: -87.8593447,
    specialties: ['Urgencias', 'Obstetricia', 'Medicina Interna', 'Cirugía General'],
  },
  {
    code: 'MINSAL-HN-031',
    name: 'Hospital Nacional General de Santa Rosa de Lima',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.MINSAL,
    department: 'La Unión',
    municipality: 'Santa Rosa de Lima',
    address: 'Carretera Ruta Militar, salida a San Miguel, Santa Rosa de Lima, La Unión',
    phone: '+503 2792-4400',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.6206222,
    longitude: -87.8968032,
    specialties: ['Atención Hospitalaria de Contención', 'Emergencias 24/7', 'Pediatría'],
  },

  // ISSS HOSPITALES (11)
  {
    code: 'ISSS-HN-001',
    name: 'Hospital Médico Quirúrgico y Oncológico',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.SPECIALIZED,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'San Salvador',
    address: '25 Avenida Norte y 25 Calle Poniente, San Salvador',
    phone: '+503 2591-5500',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.7021511,
    longitude: -89.2070264,
    specialties: ['Oncología Médica y Quirúrgica', 'Hematología', 'Cirugía Cardiovascular', 'Cuidados Intensivos'],
  },
  {
    code: 'ISSS-HN-002',
    name: 'Hospital Materno-Infantil 1º de Mayo',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.SPECIALIZED,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'San Salvador',
    address: '23 Avenida Sur y Calle Arce, San Salvador',
    phone: '+503 2591-4700',
    emergencyPhone: '+503 2591-4899',
    hasEmergency: true,
    latitude: 13.6999492,
    longitude: -89.204144,
    specialties: ['Emergencias Ginecoobstétricas', 'Perinatología', 'Neonatología de Alta Complejidad'],
  },
  {
    code: 'ISSS-HN-003',
    name: 'Hospital General ISSS',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.SPECIALIZED,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'San Salvador',
    address: 'Alameda Juan Pablo II y 25 Avenida Norte, San Salvador',
    phone: '+503 2591-4000',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.704512,
    longitude: -89.205123,
    specialties: ['Traumatología', 'Cirugía General', 'Medicina Interna', 'Unidad de Máxima Urgencia'],
  },
  {
    code: 'ISSS-HN-004',
    name: 'Hospital Amatepec ISSS',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'Soyapango',
    address: 'Urbanización Amatepec, Soyapango, San Salvador',
    phone: '+503 2591-5700',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.7001696,
    longitude: -89.1634928,
    specialties: ['Cirugía General', 'Medicina Interna', 'Ginecología', 'Obstetricia', 'Neonatología'],
  },
  {
    code: 'ISSS-HN-005',
    name: 'Hospital Policlínico Arce',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.SPECIALIZED,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'San Salvador',
    address: 'Calle Arce y 23 Avenida Sur, San Salvador',
    phone: '+503 2591-5000',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.6998,
    longitude: -89.2081,
    specialties: ['Emergencias Psiquiátricas', 'Neurología', 'Nefrología', 'Pie Diabético', 'Cirugía Plástica'],
  },
  {
    code: 'ISSS-HN-006',
    name: 'Hospital Policlínico Zacamil',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'Mejicanos',
    address: 'Colonia Zacamil, Mejicanos, San Salvador',
    phone: '+503 2591-6000',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.7319,
    longitude: -89.2152,
    specialties: ['Emergencias Adultos y Pediatría', 'Cirugía General', 'Oftalmología', 'Dermatología'],
  },
  {
    code: 'ISSS-HN-007',
    name: 'Hospital Policlínico Roma',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.SPECIALIZED,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'San Salvador',
    address: '6a-10a Calle Poniente, Colonia Roma, San Salvador',
    phone: '+503 2591-7000',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.6944033,
    longitude: -89.2251779,
    specialties: ['Emergencias Pediátricas', 'Observación Infantil', 'Cirugía Laparoscópica'],
  },
  {
    code: 'ISSS-HN-008',
    name: 'Hospital Policlínico Planes de Renderos',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.SPECIALIZED,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'Panchimalco',
    address: 'Km. 9 ½, Carretera a Los Planes de Renderos, Panchimalco, San Salvador',
    phone: '+503 2280-2000',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.647211,
    longitude: -89.194598,
    specialties: ['Rehabilitación Física Integral', 'Terapia de Lenguaje y Ocupacional'],
  },
  {
    code: 'ISSS-HN-009',
    name: 'Hospital Regional de Santa Ana ISSS',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.REGIONAL,
    operator: EstablishmentOperator.ISSS,
    department: 'Santa Ana',
    municipality: 'Santa Ana',
    address: 'Final 6a Avenida Sur, Santa Ana',
    phone: '+503 2484-4000',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.9763156,
    longitude: -89.5671711,
    specialties: ['Cuidados Intensivos', 'Cirugía', 'Maternidad', 'Pediatría', 'Traumatología'],
  },
  {
    code: 'ISSS-HN-010',
    name: 'Hospital Regional de Sonsonate ISSS',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.REGIONAL,
    operator: EstablishmentOperator.ISSS,
    department: 'Sonsonate',
    municipality: 'Sonsonate',
    address: 'Paseo 15 de Septiembre, Sonsonate',
    phone: '+503 2483-3000',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.7108578,
    longitude: -89.7273168,
    specialties: ['Medicina Interna', 'Cirugía General', 'Ortopedia', 'Cardiología', 'Perinatología'],
  },
  {
    code: 'ISSS-HN-011',
    name: 'Hospital Regional de San Miguel ISSS',
    type: EstablishmentType.HOSPITAL,
    level: EstablishmentLevel.REGIONAL,
    operator: EstablishmentOperator.ISSS,
    department: 'San Miguel',
    municipality: 'San Miguel',
    address: 'Avenida Roosevelt Sur, San Miguel',
    phone: '+503 2660-5000',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.473056,
    longitude: -88.182222,
    specialties: ['Cirugía', 'Ginecología y Obstetricia', 'Cuidados Intensivos', 'Neonatología'],
  },
];

// =========================================================================
// 2. CATÁLOGO OFICIAL DE UNIDADES MÉDICAS ISSS (26)
// =========================================================================
const verifiedISSSHealthUnits: EstablishmentSeedRecord[] = [
  {
    code: 'ISSS-UM-001',
    name: 'Unidad Médica 15 de Septiembre (Santa Anita)',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'San Salvador',
    address: 'Calle Francisco Menéndez, entre 19ª y 21ª Avenida Sur, Barrio Santa Anita, frente a la Escuela República del Ecuador.',
    phone: '2593-0015; 2593-0016; 2593-0017; 2593-0025',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.6885,
    longitude: -89.1950,
    specialties: [],
  },
  {
    code: 'ISSS-UM-002',
    name: 'Unidad Médica Aguilares',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'Aguilares',
    address: 'Carretera Troncal del Norte Km. 33, 2ª Calle Oriente, Casa #2, Aguilares. ½ cuadra antes de la gasolinera Shell.',
    phone: '2990-2002',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.9575,
    longitude: -89.1892,
    specialties: [],
  },
  {
    code: 'ISSS-UM-003',
    name: 'Unidad Médica Apopa',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'Apopa',
    address: 'Km. 13 1/2 Carretera Antigua a Quezaltepeque, final Calle La Ronda y Cuarta Avenida Sur, contiguo al Mercado Municipal.',
    phone: '2591-4300',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.8062,
    longitude: -89.1795,
    specialties: [],
  },
  {
    code: 'ISSS-UM-004',
    name: 'Unidad Médica Atlacatl',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'San Salvador',
    address: '29ª Calle Poniente, Pasaje Cipactly, Colonia Atlacatl. A la par del INFRAMEN.',
    phone: '2591-6505',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.7125,
    longitude: -89.1850,
    specialties: [],
  },
  {
    code: 'ISSS-UM-005',
    name: 'Unidad Médica Ilopango',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'Ilopango',
    address: 'Km. 8½ Boulevard del Ejército Nacional, 200 m al poniente de Cárcel de Mujeres y frente a Cartonera Centroamericana, Ilopango.',
    phone: '2591-6000',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.6980,
    longitude: -89.1150,
    specialties: [],
  },
  {
    code: 'ISSS-UM-006',
    name: 'Unidad Médica Medicina Física y Rehabilitación',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.SPECIALIZED,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'San Salvador',
    address: 'Alameda Juan Pablo II y final Calle Guadalupe, esquina opuesta a la USAM, frente a Puerto Bus.',
    phone: '2593-0036 / 2593-0037 / 2593-0038 / 2593-0039',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.7035,
    longitude: -89.2010,
    specialties: ['Medicina Física', 'Rehabilitación', 'Terapia Física', 'Terapia Ocupacional'],
  },
  {
    code: 'ISSS-UM-007',
    name: 'Unidad Médica San Jacinto',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'San Salvador',
    address: 'Avenida Barberena #1236, Barrio San Jacinto, San Salvador. A un costado del Hogar del Niño.',
    phone: '2593-0026; 2593-0027; 2593-0028; 2593-0033',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.6840,
    longitude: -89.1840,
    specialties: [],
  },
  {
    code: 'ISSS-UM-008',
    name: 'Unidad Médica Soyapango',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'Soyapango',
    address: 'Carretera de Oro, Km. 22 y 1/2, Avenida Prusia, Prados de Venecia 3, Soyapango. Contiguo a gasolinera Texaco.',
    phone: '2591-5200',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.7120,
    longitude: -89.1380,
    specialties: [],
  },
  {
    code: 'ISSS-UM-009',
    name: 'Unidad Médica Ahuachapán',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.ISSS,
    department: 'Ahuachapán',
    municipality: 'Ahuachapán',
    address: 'Final 10ª Calle Oriente y Carretera a Sonsonate.',
    phone: '2890-0147 / 2890-0148',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.9240,
    longitude: -89.8450,
    specialties: [],
  },
  {
    code: 'ISSS-UM-010',
    name: 'Unidad Médica Chalatenango',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.ISSS,
    department: 'Chalatenango',
    municipality: 'Chalatenango',
    address: '6ª Calle Poniente, Barrio El Chile, Chalatenango. Frente a Cajas de Crédito.',
    phone: '2990-0057',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 14.0415,
    longitude: -88.9350,
    specialties: [],
  },
  {
    code: 'ISSS-UM-011',
    name: 'Unidad Médica Ilobasco',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'Cabañas',
    municipality: 'Ilobasco',
    address: 'Final Avenida Carlos Bonilla #17, Barrio El Calvario, Ilobasco.',
    phone: '2990-2011 / 2990-2012',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.8435,
    longitude: -88.8540,
    specialties: [],
  },
  {
    code: 'ISSS-UM-012',
    name: 'Unidad Médica Sensuntepeque',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'Cabañas',
    municipality: 'Sensuntepeque',
    address: '3ª Calle Oriente y final Avenida Libertad #1, Barrio Los Remedios.',
    phone: '2990-0037 / 2990-0038',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.8765,
    longitude: -88.6320,
    specialties: [],
  },
  {
    code: 'ISSS-UM-013',
    name: 'Unidad Médica Cojutepeque',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.ISSS,
    department: 'Cuscatlán',
    municipality: 'Cojutepeque',
    address: 'Carretera Panamericana Km. 33.5, Colonia Las Colinas, Calle Principal Polígono "A", Casas #9 y #10.',
    phone: '2990-2007',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.7220,
    longitude: -88.9340,
    specialties: [],
  },
  {
    code: 'ISSS-UM-014',
    name: 'Unidad Médica La Libertad',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'La Libertad',
    municipality: 'La Libertad',
    address: '2ª Calle Poniente y 5ª Avenida Sur, Puerto de La Libertad. Esquina opuesta a la Escuela El Calvario.',
    phone: '2990-2016',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.4880,
    longitude: -89.3220,
    specialties: [],
  },
  {
    code: 'ISSS-UM-015',
    name: 'Unidad Médica Quezaltepeque',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.ISSS,
    department: 'La Libertad',
    municipality: 'Quezaltepeque',
    address: 'Final Calle Emilia Melcher #76. Una cuadra después de la Unidad de Salud y a 2 cuadras del Penal.',
    phone: '2990-0300 / 2990-0301',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.8325,
    longitude: -89.2730,
    specialties: [],
  },
  {
    code: 'ISSS-UM-016',
    name: 'Unidad Médica Ateos (Sacacoyo)',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'La Libertad',
    municipality: 'Sacacoyo',
    address: 'Carretera a Sonsonate Km. 30½, Cantón Ateos, Sacacoyo, contiguo a gasolinera Texaco.',
    phone: '2990-2006',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.7420,
    longitude: -89.4120,
    specialties: [],
  },
  {
    code: 'ISSS-UM-017',
    name: 'Unidad Médica Santa Tecla (Ex APAC)',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.ISSS,
    department: 'La Libertad',
    municipality: 'Santa Tecla',
    address: '4ª Calle Oriente, Colonia Utila, entre Av. Zablah Touche y 13 Av. Sur, 7-6 Santa Tecla.',
    phone: '2593-0300',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.6730,
    longitude: -89.2850,
    specialties: [],
  },
  {
    code: 'ISSS-UM-018',
    name: 'Unidad Médica Zacatecoluca',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.ISSS,
    department: 'La Paz',
    municipality: 'Zacatecoluca',
    address: '7ª Calle Oriente #56, Colonia Las Margaritas, Barrio San José, Zacatecoluca.',
    phone: '2990-0052 / 2990-0054 / 2990-0056',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.5040,
    longitude: -88.8710,
    specialties: [],
  },
  {
    code: 'ISSS-UM-019',
    name: 'Unidad Médica La Unión',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.ISSS,
    department: 'La Unión',
    municipality: 'La Unión',
    address: '3ª Calle Poniente 6-37, Barrio San Carlos, La Unión. Sobre Carretera Panamericana.',
    phone: '2790-0027 / 2790-0030',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.3360,
    longitude: -87.8440,
    specialties: [],
  },
  {
    code: 'ISSS-UM-020',
    name: 'Unidad Médica Santa Ana',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.ISSS,
    department: 'Santa Ana',
    municipality: 'Santa Ana',
    address: 'Ave. José Matías Delgado entre 6 y 8 Calle Poniente (ex-Colegio San José).',
    phone: '2890-0800',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.9920,
    longitude: -89.5580,
    specialties: [],
  },
  {
    code: 'ISSS-UM-021',
    name: 'Unidad Médica Acajutla',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'Sonsonate',
    municipality: 'Acajutla',
    address: 'Colonia Acacsual, Calle Principal y Avenida Pedro de Alvarado.',
    phone: '2890-3008',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.5925,
    longitude: -89.8315,
    specialties: [],
  },
  {
    code: 'ISSS-UM-022',
    name: 'Unidad Médica Juayúa',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'Sonsonate',
    municipality: 'Juayúa',
    address: '1ª Calle Poniente y 2ª Avenida Norte, Barrio El Carmen, Juayúa.',
    phone: '2890-3013 / 2890-3023',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.8410,
    longitude: -89.7450,
    specialties: [],
  },
  {
    code: 'ISSS-UM-023',
    name: 'Unidad Médica Berlín',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'Usulután',
    municipality: 'Berlín',
    address: '1ª Calle Poniente, Barrio El Centro, Casa #4, Berlín, Usulután.',
    phone: '2790-2002 / 2790-2003',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.5020,
    longitude: -88.5330,
    specialties: [],
  },
  {
    code: 'ISSS-UM-024',
    name: 'Unidad Médica Puerto El Triunfo',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'Usulután',
    municipality: 'Puerto El Triunfo',
    address: '1ª Avenida Norte y 2ª Calle Poniente #3, Puerto El Triunfo, Usulután.',
    phone: '2790-2006',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.2840,
    longitude: -88.5520,
    specialties: [],
  },
  {
    code: 'ISSS-UM-025',
    name: 'Unidad Médica Santiago de María',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.ISSS,
    department: 'Usulután',
    municipality: 'Santiago de María',
    address: 'Barrio La Parroquia, Santiago de María, antiguo Hotel Los Gramales Inn.',
    phone: '2790-2011 / 2663-0564',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.4830,
    longitude: -88.4710,
    specialties: [],
  },
  {
    code: 'ISSS-UM-026',
    name: 'Unidad Médica Usulután',
    type: EstablishmentType.HEALTH_CENTER,
    level: EstablishmentLevel.DEPARTMENTAL,
    operator: EstablishmentOperator.ISSS,
    department: 'Usulután',
    municipality: 'Usulután',
    address: '7ª Avenida Norte y 8ª Calle Poniente, Barrio La Merced, Usulután.',
    phone: '2790-0040 / 2790-0041 / 2790-0042 / 2790-0043',
    emergencyPhone: null,
    hasEmergency: true,
    latitude: 13.3450,
    longitude: -88.4410,
    specialties: [],
  },
];

// =========================================================================
// 3. CATÁLOGO OFICIAL DE CLÍNICAS COMUNALES ISSS (35)
// =========================================================================
const verifiedCommunalClinics: EstablishmentSeedRecord[] = [
  {
    code: 'ISSS-CC-001',
    name: 'Clínica Comunal Guadalupe',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'Apopa',
    address: 'Entrada a Col. Cuscatlán, Calle Principal, Casa #510, detrás de Pizza Hut Pericentro Apopa.',
    phone: '2591-2181',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.8055,
    longitude: -89.1788,
    specialties: [],
  },
  {
    code: 'ISSS-CC-002',
    name: 'Clínica Comunal Ayutuxtepeque',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'Ayutuxtepeque',
    address: '29 Av. Norte, Calle Principal #84, Col. Scandia, Ayutuxtepeque. Referencia: entrada de la Col. Scandia.',
    phone: '2593-0005',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.7431,
    longitude: -89.2067,
    specialties: [],
  },
  {
    code: 'ISSS-CC-003',
    name: 'Clínica Comunal Cuscatancingo',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'Cuscatancingo',
    address: 'Calle Bolívar y Pasaje "A", #7, Col. Santa Rosa, Cuscatancingo.',
    phone: '2593-0008',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.7378,
    longitude: -89.1822,
    specialties: [],
  },
  {
    code: 'ISSS-CC-004',
    name: 'Clínica Comunal Ciudad Delgado',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'Delgado',
    address: 'Avenida Paleca #8, Ciudad Delgado. Después (abajo) de la Plaza del Mercado.',
    phone: '2593-0006',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.7225,
    longitude: -89.1706,
    specialties: [],
  },
  {
    code: 'ISSS-CC-005',
    name: 'Clínica Comunal Santa Lucia',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'Ilopango',
    address: 'Prolongación Calle Principal #66-C, Col. Santa Lucía.',
    phone: '2591-2147',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.7022,
    longitude: -89.1245,
    specialties: [],
  },
  {
    code: 'ISSS-CC-006',
    name: 'Clínica Comunal San Cristobal',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'Ilopango',
    address: 'Calle Francisco Meléndez, Barrio El Centro #3, Ilopango.',
    phone: '2295-0918',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.7011,
    longitude: -89.1092,
    specialties: [],
  },
  {
    code: 'ISSS-CC-007',
    name: 'Clínica Comunal Mejicanos',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'Mejicanos',
    address: 'Col. Palmira, Pasaje Honduras, Calle El Roble "A", N°24, Mejicanos.',
    phone: '2593-0002 / 2593-0009',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.738,
    longitude: -89.213,
    specialties: [],
  },
  {
    code: 'ISSS-CC-008',
    name: 'Clínica Comunal Virgen del Transito',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'Mejicanos',
    address: 'Final 5ª Avenida Norte #27-B, Colonia Alfaro, Mejicanos.',
    phone: '2591-2145',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.7315,
    longitude: -89.214,
    specialties: [],
  },
  {
    code: 'ISSS-CC-009',
    name: 'Clínica Comunal Las Victorias',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'Mejicanos',
    address: '35ª Avenida Norte, Reparto Santa Fe, No. 6, San Salvador.',
    phone: '2235-1449',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.7205,
    longitude: -89.2185,
    specialties: [],
  },
  {
    code: 'ISSS-CC-010',
    name: 'Clínica Comunal San Marcos',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'San Marcos',
    address: 'Calle 25 de Abril Poniente y 3 Av. Norte, #125, Barrio San José, San Marcos.',
    phone: '2213-0200',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.6592,
    longitude: -89.1831,
    specialties: [],
  },
  {
    code: 'ISSS-CC-011',
    name: 'Clínica Comunal San Martin',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'San Martín',
    address: '3ª Calle Poniente y Calle Principal, Col. San Joaquín #17 y 17 Bis, San Martín.',
    phone: '2593-0013',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.7428,
    longitude: -89.0558,
    specialties: [],
  },
  {
    code: 'ISSS-CC-012',
    name: 'Clínica Comunal San Miguelito',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'San Salvador',
    address: '1ª Avenida Norte #1256, entre 21 y 23 Calle Poniente.',
    phone: '2591-2158',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.7083,
    longitude: -89.1925,
    specialties: [],
  },
  {
    code: 'ISSS-CC-013',
    name: 'Clínica Comunal La Rabida',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'San Salvador',
    address: 'Pasaje El Refugio #131 entre 35 y 37 Calle Oriente, Col. La Rábida.',
    phone: '2591-2160',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.7142,
    longitude: -89.1878,
    specialties: [],
  },
  {
    code: 'ISSS-CC-014',
    name: 'Clínica Comunal San Antonio Abad',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'San Salvador',
    address: 'Calle San Antonio Abad, Av. Lisboa #771.',
    phone: '2591-2142',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.722,
    longitude: -89.2325,
    specialties: [],
  },
  {
    code: 'ISSS-CC-015',
    name: 'Clínica Comunal Miramonte',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'San Salvador',
    address: 'Colonia Miramonte y Avenida Sierra Nevada #618, frente a Casa Miriam.',
    phone: '2591-2144',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.7075,
    longitude: -89.2195,
    specialties: [],
  },
  {
    code: 'ISSS-CC-016',
    name: 'Clínica Comunal Monserrat',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'San Salvador',
    address: 'Calle Monserrat, antiguo plantel de IVU, Ciudadela Monserrat ISSS.',
    phone: '2591-6838',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.6872,
    longitude: -89.212,
    specialties: [],
  },
  {
    code: 'ISSS-CC-017',
    name: 'Clínica Comunal Costa Rica',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'San Salvador',
    address: 'Avenida Irazú y Calle Juan Mora #306, Colonia Costa Rica.',
    phone: '2270-0248',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.6811,
    longitude: -89.1915,
    specialties: [],
  },
  {
    code: 'ISSS-CC-018',
    name: 'Clínica Comunal Santo Tomas',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'Santo Tomás',
    address: 'Barrio El Calvario, Calle Alberto Masferrer, Casa #16, Santo Tomás.',
    phone: '2593-0014',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.6408,
    longitude: -89.1333,
    specialties: [],
  },
  {
    code: 'ISSS-CC-019',
    name: 'Clínica Comunal Monte Maria',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'Soyapango',
    address: 'Reparto Monte María II, Pasaje 3, Casa #1, Soyapango.',
    phone: '2293-4902',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.705,
    longitude: -89.143,
    specialties: [],
  },
  {
    code: 'ISSS-CC-020',
    name: 'Clínica Comunal San Jose',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'Soyapango',
    address: 'Polígono "D", Lote #1, Lotificación Alta Vista, Residencial Alta Vista, Ilopango.',
    phone: '2593-0011',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.728,
    longitude: -89.098,
    specialties: [],
  },
  {
    code: 'ISSS-CC-021',
    name: 'Clínica Comunal Morazan',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Salvador',
    municipality: 'Soyapango',
    address: 'Calle Xochimilco #3, Repto. Guadalupe, Soyapango. Frente a Escuela María Auxiliadora.',
    phone: '2277-0759',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.6965,
    longitude: -89.148,
    specialties: [],
  },
  {
    code: 'ISSS-CC-022',
    name: 'Clínica Comunal El Calvario',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'Ahuachapán',
    municipality: 'Ahuachapán',
    address: '2ª Avenida Norte #2-7, Barrio El Calvario, Ahuachapán.',
    phone: '2890-0126',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.9214,
    longitude: -89.8467,
    specialties: [],
  },
  {
    code: 'ISSS-CC-023',
    name: 'Clínica Comunal Lourdes Colon',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'La Libertad',
    municipality: 'Colón',
    address: 'Km 23 y ½ carretera a Sonsonate, Lourdes Colón.',
    phone: '2338-4054',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.7231,
    longitude: -89.3639,
    specialties: [],
  },
  {
    code: 'ISSS-CC-024',
    name: 'Clínica Comunal Sitio del Niño',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'La Libertad',
    municipality: 'San Juan Opico',
    address: 'Avenida Principal, Calle N°2 Casa #24, Col. Sitio del Niño, San Juan Opico.',
    phone: '2990-2000',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.7889,
    longitude: -89.3514,
    specialties: [],
  },
  {
    code: 'ISSS-CC-025',
    name: 'Clínica Comunal Antiguo Cuscatlan',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'La Libertad',
    municipality: 'Santa Tecla',
    address: 'Col. La Sultana 2, Avenida Antiguo Cuscatlán, Calle Los Claveles 2, Casa Nº9, Antiguo Cuscatlán.',
    phone: '2593-0004',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.6764,
    longitude: -89.2486,
    specialties: [],
  },
  {
    code: 'ISSS-CC-026',
    name: 'Clínica Comunal Ciudad Merliot',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'La Libertad',
    municipality: 'Santa Tecla',
    address: 'Boulevard Merliot, Polígono "C", Casa #4, Urb. Jardines de La Libertad, Santa Tecla.',
    phone: '2591-2180',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.678,
    longitude: -89.272,
    specialties: [],
  },
  {
    code: 'ISSS-CC-027',
    name: 'Clínica Comunal San Antonio',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'La Libertad',
    municipality: 'Santa Tecla',
    address: '1 Av. Norte 2-6 entre 1ª y 3ª Calle Poniente, Barrio Belén, Santa Tecla.',
    phone: '2591-2175',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.6739,
    longitude: -89.2889,
    specialties: [],
  },
  {
    code: 'ISSS-CC-028',
    name: 'Clínica Comunal Santa Monica',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'La Libertad',
    municipality: 'Santa Tecla',
    address: '9ª Calle Oriente, Polígono 17, Casa #6, Ciudad Merliot.',
    phone: '2229-8880',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.6795,
    longitude: -89.266,
    specialties: [],
  },
  {
    code: 'ISSS-CC-029',
    name: 'Clínica Comunal Olocuilta',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'La Paz',
    municipality: 'Olocuilta',
    address: 'Barrio El Carmen, Calle La Tejera (calle al cementerio) #3, Olocuilta.',
    phone: '2990-2023',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.565,
    longitude: -89.1172,
    specialties: [],
  },
  {
    code: 'ISSS-CC-030',
    name: 'Clínica Comunal Santa Rosa de Lima',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'La Unión',
    municipality: 'Santa Rosa de Lima',
    address: 'Avenida Fernando Benítez, Barrio Las Delicias, Santa Rosa de Lima.',
    phone: '2656-6753',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.6247,
    longitude: -87.8936,
    specialties: [],
  },
  {
    code: 'ISSS-CC-031',
    name: 'Clínica Comunal Barrio San Francisco',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Miguel',
    municipality: 'San Miguel',
    address: '5ª Avenida Norte #501-A, Barrio San Francisco, San Miguel.',
    phone: '2790-0023 / 2790-0022',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.486,
    longitude: -88.175,
    specialties: [],
  },
  {
    code: 'ISSS-CC-032',
    name: 'Clínica Comunal Panamericana',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'San Miguel',
    municipality: 'San Miguel',
    address: '17 Calle Poniente número 104, Barrio San Nicolás, San Miguel.',
    phone: '2640-1946',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.4795,
    longitude: -88.181,
    specialties: [],
  },
  {
    code: 'ISSS-CC-033',
    name: 'Clínica Comunal San Rafael',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'Santa Ana',
    municipality: 'Chalchuapa',
    address: 'Final 23 Avenida Sur, entre 9ª y 11ª Calle Oriente.',
    phone: '2890-3006',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.9867,
    longitude: -89.6806,
    specialties: [],
  },
  {
    code: 'ISSS-CC-034',
    name: 'Clínica Comunal Santa Barbara',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'Santa Ana',
    municipality: 'Santa Ana',
    address: '6ª Avenida Sur, entre 7ª y 9ª Calle Poniente #29, Santa Ana.',
    phone: '2890-0114',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.9942,
    longitude: -89.5597,
    specialties: [],
  },
  {
    code: 'ISSS-CC-035',
    name: 'Clínica Comunal Santo Domingo',
    type: EstablishmentType.CLINIC,
    level: EstablishmentLevel.BASIC,
    operator: EstablishmentOperator.ISSS,
    department: 'Sonsonate',
    municipality: 'Sonsonate',
    address: 'Final 23 Avenida Sur, entre 9ª y 11ª Calle Oriente.',
    phone: '2890-3006',
    emergencyPhone: null,
    hasEmergency: false,
    latitude: 13.7189,
    longitude: -89.7242,
    specialties: [],
  },
];

// =========================================================================
// FUNCIÓN PRINCIPAL DE SEMBRADO
// =========================================================================
async function main() {
  console.log('🌱 Iniciando sembrado maestro de datos para MedicOS...');

  const now = new Date();
  const fechaHaceMinutos = (minutos: number): Date => new Date(now.getTime() - minutos * 60 * 1000);
  const fechaHaceHoras = (horas: number): Date => new Date(now.getTime() - horas * 60 * 60 * 1000);

  // -----------------------------------------------------------------------
  // 1. Sembrado del Catálogo Oficial Nacional (103 Establecimientos)
  // -----------------------------------------------------------------------
  console.log('🧹 Limpiando y reconstruyendo catálogo oficial de establecimientos...');
  await prisma.establishment.deleteMany({});

  const allEstablishments = [
    ...verifiedNationalHospitals,
    ...verifiedISSSHealthUnits,
    ...verifiedCommunalClinics,
  ];

  for (const est of allEstablishments) {
    await prisma.establishment.create({
      data: {
        code: est.code,
        name: est.name,
        type: est.type,
        level: est.level,
        operator: est.operator,
        department: est.department,
        municipality: est.municipality,
        address: est.address,
        phone: est.phone,
        emergencyPhone: est.emergencyPhone,
        hasEmergency: est.hasEmergency,
        latitude: est.latitude,
        longitude: est.longitude,
        specialties: est.specialties,
        totalBeds: 0,
        availableBeds: 0,
        status: EstablishmentStatus.OPERATIONAL,
        syncStatus: SyncStatus.SYNCED,
        version: 1,
        originDeviceId: SYSTEM_DEVICE_ID,
        lastModifiedByDeviceId: SYSTEM_DEVICE_ID,
      },
    });
  }

  const totalEstablecimientos = await prisma.establishment.count();
  console.log(`✅ Catálogo oficial sembrado exitosamente: ${totalEstablecimientos} establecimientos registrados.`);

  // -----------------------------------------------------------------------
  // 2. Registrar Dispositivos del Sistema (Infraestructura y Red)
  // -----------------------------------------------------------------------
  const centralDevice = await prisma.device.upsert({
    where: { serialNumber: 'DEV-CENTRAL-01' },
    update: { status: DeviceStatus.ACTIVE },
    create: {
      name: 'Servidor Central - MedicOS',
      serialNumber: 'DEV-CENTRAL-01',
      operatingSystem: 'Ubuntu 24.04 LTS',
      appVersion: '1.0.0',
      location: 'Sede Central San Salvador',
      status: DeviceStatus.ACTIVE,
    },
  });

  const mobileDevice1 = await prisma.device.upsert({
    where: { serialNumber: 'DEV-MOB-TEPEZONTES-01' },
    update: { status: DeviceStatus.ACTIVE },
    create: {
      name: 'Tablet Brigada Tepezontes #1',
      serialNumber: 'DEV-MOB-TEPEZONTES-01',
      operatingSystem: 'Android 14 / MedicOS Mobile',
      appVersion: '1.0.0',
      location: 'San Miguel Tepezontes, La Paz',
      status: DeviceStatus.ACTIVE,
    },
  });

  await prisma.device.upsert({
    where: { serialNumber: 'DEV-MOB-LAPAZ-01' },
    update: { status: DeviceStatus.OFFLINE },
    create: {
      name: 'Tablet Brigada La Paz #1',
      serialNumber: 'DEV-MOB-LAPAZ-01',
      operatingSystem: 'Android 14 / MedicOS Mobile',
      appVersion: '1.0.0',
      location: 'La Paz',
      status: DeviceStatus.OFFLINE,
    },
  });

  console.log('✅ Nodos de red/dispositivos registrados (Activos y Offline)');

  // -----------------------------------------------------------------------
  // 3. Generar Usuarios del Sistema (IAM)
  // -----------------------------------------------------------------------
  const adminPasswordHash = await bcrypt.hash('Admin2026!Medicos', 10);
  const patientPasswordHash = await bcrypt.hash('Paciente2026!Medicos', 10);

  const adminUser = await prisma.user.upsert({
    where: { email: 'admin@medicos.org' },
    update: {},
    create: {
      email: 'admin@medicos.org',
      passwordHash: adminPasswordHash,
      role: Role.ADMIN,
      status: UserStatus.ACTIVE,
      firstName: 'Administrador',
      lastName: 'Central',
      phone: '+503 7000-0001',
    },
  });

  const doctorUser = await prisma.user.upsert({
    where: { email: 'doctora.martinez@medicos.org' },
    update: {},
    create: {
      email: 'doctora.martinez@medicos.org',
      passwordHash: adminPasswordHash,
      role: Role.DOCTOR,
      status: UserStatus.ACTIVE,
      firstName: 'Elena',
      lastName: 'Martínez',
      phone: '+503 7000-0002',
    },
  });

  const brigadistaUser = await prisma.user.upsert({
    where: { email: 'brigadista.perez@medicos.org' },
    update: {},
    create: {
      email: 'brigadista.perez@medicos.org',
      passwordHash: adminPasswordHash,
      role: Role.BRIGADISTA,
      status: UserStatus.ACTIVE,
      firstName: 'Carlos',
      lastName: 'Pérez',
      phone: '+503 7000-0003',
    },
  });

  const authorityUser = await prisma.user.upsert({
    where: { email: 'autoridad.salud@minsal.gob.sv' },
    update: {},
    create: {
      email: 'autoridad.salud@minsal.gob.sv',
      passwordHash: adminPasswordHash,
      role: Role.AUTHORITY,
      status: UserStatus.ACTIVE,
      firstName: 'Patricia',
      lastName: 'Rivas',
      phone: '+503 7000-0004',
    },
  });

  const patientUser1 = await prisma.user.upsert({
    where: { email: 'maria.gonzalez@paciente.medicos.org' },
    update: {},
    create: {
      email: 'maria.gonzalez@paciente.medicos.org',
      passwordHash: patientPasswordHash,
      role: Role.PATIENT,
      status: UserStatus.ACTIVE,
      firstName: 'María',
      lastName: 'González',
      phone: '+503 7123-4567',
    },
  });

  const patientUser2 = await prisma.user.upsert({
    where: { email: 'carlos.ruiz@paciente.medicos.org' },
    update: {},
    create: {
      email: 'carlos.ruiz@paciente.medicos.org',
      passwordHash: patientPasswordHash,
      role: Role.PATIENT,
      status: UserStatus.ACTIVE,
      firstName: 'Carlos',
      lastName: 'Ruiz',
      phone: '+503 7234-8899',
    },
  });

  const patientUser3 = await prisma.user.upsert({
    where: { email: 'ana.rodriguez@paciente.medicos.org' },
    update: {},
    create: {
      email: 'ana.rodriguez@paciente.medicos.org',
      passwordHash: patientPasswordHash,
      role: Role.PATIENT,
      status: UserStatus.ACTIVE,
      firstName: 'Ana',
      lastName: 'Rodríguez',
      phone: '+503 7888-1122',
    },
  });

  const patientUser4 = await prisma.user.upsert({
    where: { email: 'jorge.martinez@paciente.medicos.org' },
    update: {},
    create: {
      email: 'jorge.martinez@paciente.medicos.org',
      passwordHash: patientPasswordHash,
      role: Role.PATIENT,
      status: UserStatus.ACTIVE,
      firstName: 'Jorge',
      lastName: 'Martínez',
      phone: '+503 7555-9900',
    },
  });

  console.log('✅ Usuarios del sistema creados (ADMIN, DOCTOR, BRIGADISTA, AUTHORITY, PATIENTS)');

  // -----------------------------------------------------------------------
  // 4. Crear o Actualizar Brigada Médica
  // -----------------------------------------------------------------------
  let brigade = await prisma.brigade.findFirst({
    where: { name: 'Brigada Médica San Miguel Tepezontes 2026' },
  });

  if (!brigade) {
    brigade = await prisma.brigade.create({
      data: {
        name: 'Brigada Médica San Miguel Tepezontes 2026',
        department: 'La Paz',
        municipality: 'San Miguel Tepezontes',
        latitude: 13.6236,
        longitude: -89.0142,
        status: BrigadeStatus.ACTIVE,
        startDate: fechaHaceHoras(24),
        endDate: new Date(now.getTime() + 23 * 24 * 60 * 60 * 1000),
        leaderId: adminUser.id,
        originDeviceId: centralDevice.id,
        lastModifiedByDeviceId: centralDevice.id,
        members: {
          create: [{ userId: doctorUser.id }, { userId: brigadistaUser.id }],
        },
      },
    });
  } else {
    brigade = await prisma.brigade.update({
      where: { id: brigade.id },
      data: {
        status: BrigadeStatus.ACTIVE,
        startDate: fechaHaceHoras(24),
        endDate: new Date(now.getTime() + 23 * 24 * 60 * 60 * 1000),
      },
    });
  }
  console.log(`✅ Brigada activa para hoy: ${brigade.name}`);

  // -----------------------------------------------------------------------
  // 5. Crear Pacientes y Expedientes Clínicos
  // -----------------------------------------------------------------------
  const pacientesData: PacienteSeedData[] = [
    {
      userId: patientUser1.id,
      firstName: 'María',
      lastName: 'González',
      dui: '01234567-8',
      dob: new Date('1985-05-15T00:00:00Z'),
      sex: Sex.FEMALE,
      phone: '+503 7123-4567',
      address: 'Barrio El Centro, Calle Principal, San Miguel Tepezontes',
      bloodType: BloodType.O_POSITIVE,
      familyHistory: 'Diabetes Mellitus Tipo 2 (Madre)',
      createdAt: fechaHaceMinutos(180),
    },
    {
      userId: patientUser2.id,
      firstName: 'Carlos',
      lastName: 'Ruiz',
      dui: '02345678-9',
      dob: new Date('1978-09-20T00:00:00Z'),
      sex: Sex.MALE,
      phone: '+503 7234-8899',
      address: 'Caserío El Calvario, San Miguel Tepezontes',
      bloodType: BloodType.A_POSITIVE,
      familyHistory: 'Hipertensión Arterial (Padre)',
      createdAt: fechaHaceMinutos(120),
    },
    {
      userId: patientUser3.id,
      firstName: 'Ana',
      lastName: 'Rodríguez',
      dui: '03456789-0',
      dob: new Date('1992-11-10T00:00:00Z'),
      sex: Sex.FEMALE,
      phone: '+503 7888-1122',
      address: 'Cantón La Cruz, San Miguel Tepezontes',
      bloodType: BloodType.O_POSITIVE,
      familyHistory: 'Sin antecedentes relevantes',
      createdAt: fechaHaceMinutos(60),
    },
    {
      userId: patientUser4.id,
      firstName: 'Jorge',
      lastName: 'Martínez',
      dui: '04567890-1',
      dob: new Date('1965-03-04T00:00:00Z'),
      sex: Sex.MALE,
      phone: '+503 7555-9900',
      address: 'Barrio San José, San Miguel Tepezontes',
      bloodType: BloodType.O_NEGATIVE,
      familyHistory: 'Cardiopatía isquémica (Abuelo)',
      createdAt: fechaHaceMinutos(30),
    },
  ];

  const patientsList: PatientWithClinicalRecord[] = [];

  for (const p of pacientesData) {
    let patient = await prisma.patient.findFirst({
      where: { dui: p.dui },
      include: { clinicalRecord: true },
    });

    if (!patient) {
      patient = await prisma.patient.create({
        data: {
          userId: p.userId,
          firstName: p.firstName,
          lastName: p.lastName,
          dateOfBirth: p.dob,
          dui: p.dui,
          sex: p.sex,
          phone: p.phone,
          address: p.address,
          originDeviceId: mobileDevice1.id,
          lastModifiedByDeviceId: mobileDevice1.id,
          createdAt: p.createdAt,
          updatedAt: p.createdAt,
          clinicalRecord: {
            create: {
              bloodType: p.bloodType,
              familyHistory: p.familyHistory,
              originDeviceId: mobileDevice1.id,
              lastModifiedByDeviceId: mobileDevice1.id,
              createdAt: p.createdAt,
              updatedAt: p.createdAt,
            },
          },
        },
        include: { clinicalRecord: true },
      });
    } else {
      patient = await prisma.patient.update({
        where: { id: patient.id },
        data: {
          createdAt: p.createdAt,
          updatedAt: p.createdAt,
        },
        include: { clinicalRecord: true },
      });
    }

    patientsList.push(patient);
  }

  console.log('✅ Pacientes y expedientes clínicos preparados');

  // -----------------------------------------------------------------------
  // 6. Consultas del Día
  // -----------------------------------------------------------------------
  await prisma.consultation.deleteMany({});

  const followUpIn7Days = new Date(now);
  followUpIn7Days.setDate(followUpIn7Days.getDate() + 7);

  const c1 = await prisma.consultation.create({
    data: {
      patientId: patientsList[0].id,
      doctorId: doctorUser.id,
      clinicalRecordId: patientsList[0].clinicalRecord!.id,
      brigadeId: brigade.id,
      status: ConsultationStatus.COMPLETED,
      chiefComplaint: 'Cefalea frontal pulsátil de 3 días de evolución acompañada de fatiga.',
      physicalExam: 'Paciente normotensa, consciente y orientada. Sin focalización neurológica.',
      diagnosisCode: 'R51',
      diagnosisDesc: 'Cefalea tensional primaria',
      treatmentPlan: 'Paracetamol 500mg c/8h por 3 días. Hidratación adecuada.',
      consultationDate: fechaHaceMinutos(150),
      followUpDate: followUpIn7Days,
      startedAt: fechaHaceMinutos(150),
      completedAt: fechaHaceMinutos(125),
      originDeviceId: mobileDevice1.id,
      lastModifiedByDeviceId: mobileDevice1.id,
      createdAt: fechaHaceMinutos(150),
      updatedAt: fechaHaceMinutos(125),
    },
  });

  const c2 = await prisma.consultation.create({
    data: {
      patientId: patientsList[1].id,
      doctorId: doctorUser.id,
      clinicalRecordId: patientsList[1].clinicalRecord!.id,
      brigadeId: brigade.id,
      status: ConsultationStatus.IN_PROGRESS,
      chiefComplaint: 'Fiebre persistente, escalofríos y presión arterial elevada.',
      physicalExam: 'Facies febril, diaforético, campos pulmonares limpios.',
      diagnosisDesc: '',
      treatmentPlan: '',
      consultationDate: fechaHaceMinutos(90),
      startedAt: fechaHaceMinutos(90),
      originDeviceId: mobileDevice1.id,
      lastModifiedByDeviceId: mobileDevice1.id,
      createdAt: fechaHaceMinutos(90),
      updatedAt: fechaHaceMinutos(90),
    },
  });

  await prisma.consultation.create({
    data: {
      patientId: patientsList[2].id,
      doctorId: doctorUser.id,
      clinicalRecordId: patientsList[2].clinicalRecord!.id,
      brigadeId: brigade.id,
      status: ConsultationStatus.DRAFT,
      chiefComplaint: 'Evaluación general y control de signos vitales.',
      physicalExam: '',
      diagnosisDesc: '',
      treatmentPlan: '',
      consultationDate: fechaHaceMinutos(45),
      originDeviceId: mobileDevice1.id,
      lastModifiedByDeviceId: mobileDevice1.id,
      createdAt: fechaHaceMinutos(45),
      updatedAt: fechaHaceMinutos(45),
    },
  });

  await prisma.consultation.create({
    data: {
      patientId: patientsList[3].id,
      doctorId: doctorUser.id,
      clinicalRecordId: patientsList[3].clinicalRecord!.id,
      brigadeId: brigade.id,
      status: ConsultationStatus.CANCELLED,
      chiefComplaint: 'Control de rutina.',
      physicalExam: '',
      diagnosisDesc: '',
      treatmentPlan: '',
      consultationDate: fechaHaceMinutos(20),
      originDeviceId: mobileDevice1.id,
      lastModifiedByDeviceId: mobileDevice1.id,
      createdAt: fechaHaceMinutos(20),
      updatedAt: fechaHaceMinutos(20),
    },
  });

  console.log('✅ Consultas del día generadas');

  // -----------------------------------------------------------------------
  // 7. Signos Vitales
  // -----------------------------------------------------------------------
  await prisma.vitalSigns.deleteMany({});

  await prisma.vitalSigns.create({
    data: {
      patientId: patientsList[0].id,
      consultationId: c1.id,
      temperature: 36.6,
      heartRate: 75,
      oxygenSat: 98,
      systolic: 120,
      diastolic: 80,
      weight: 62.5,
      height: 1.6,
      originDeviceId: mobileDevice1.id,
      lastModifiedByDeviceId: mobileDevice1.id,
      createdAt: fechaHaceMinutos(160),
    },
  });

  await prisma.vitalSigns.create({
    data: {
      patientId: patientsList[1].id,
      consultationId: c2.id,
      temperature: 38.6,
      heartRate: 102,
      oxygenSat: 88,
      systolic: 150,
      diastolic: 95,
      weight: 78.0,
      height: 1.72,
      originDeviceId: mobileDevice1.id,
      lastModifiedByDeviceId: mobileDevice1.id,
      createdAt: fechaHaceMinutos(100),
    },
  });

  console.log('✅ Signos vitales insertados');

  // -----------------------------------------------------------------------
  // 8. Eventos de Auditoría
  // -----------------------------------------------------------------------
  await prisma.auditLog.deleteMany({});

  const auditLogsData = [
    {
      userId: adminUser.id,
      deviceId: centralDevice.id,
      action: 'LOGIN',
      entity: 'User',
      entityId: adminUser.id,
      changedFields: { message: 'Inicio de sesión exitoso en el portal administrativo' },
      ipAddress: '127.0.0.1',
      createdAt: fechaHaceMinutos(15),
    },
    {
      userId: authorityUser.id,
      deviceId: centralDevice.id,
      action: 'LOGIN',
      entity: 'User',
      entityId: authorityUser.id,
      changedFields: { message: 'Inicio de sesión exitoso en el portal de autoridad sanitaria' },
      ipAddress: '127.0.0.1',
      createdAt: fechaHaceMinutos(10),
    },
    {
      userId: brigadistaUser.id,
      deviceId: mobileDevice1.id,
      action: 'PATIENT_CREATE',
      entity: 'Patient',
      entityId: patientsList[0].id,
      changedFields: { message: 'Registro de expediente clínico para paciente María González' },
      ipAddress: '192.168.1.45',
      createdAt: fechaHaceMinutos(45),
    },
    {
      userId: doctorUser.id,
      deviceId: mobileDevice1.id,
      action: 'CONSULTATION_CREATE',
      entity: 'Consultation',
      entityId: c1.id,
      changedFields: { message: 'Registro de consulta médica y prescripción de tratamiento' },
      ipAddress: '192.168.1.45',
      createdAt: fechaHaceMinutos(120),
    },
  ];

  for (const log of auditLogsData) {
    await prisma.auditLog.create({ data: log });
  }

  // -----------------------------------------------------------------------
  // 9. Cola Outbox (Sincronización Offline-First)
  // -----------------------------------------------------------------------
  await prisma.syncQueue.deleteMany({});

  const syncQueueData = [
    {
      deviceId: mobileDevice1.id,
      entity: 'Patient',
      entityId: patientsList[0].id,
      operation: SyncOperation.CREATE,
      payload: JSON.stringify({ patientId: patientsList[0].id, name: 'María González' }),
      status: QueueStatus.PENDING,
      retryCount: 0,
      createdAt: fechaHaceMinutos(10),
    },
    {
      deviceId: centralDevice.id,
      entity: 'Consultation',
      entityId: c1.id,
      operation: SyncOperation.UPDATE,
      payload: JSON.stringify({ consultationId: c1.id }),
      status: QueueStatus.COMPLETED,
      retryCount: 1,
      createdAt: fechaHaceMinutos(60),
    },
  ];

  for (const item of syncQueueData) {
    await prisma.syncQueue.create({ data: item });
  }

  // -----------------------------------------------------------------------
  // 10. Reconstruir Jornada Activa
  // -----------------------------------------------------------------------
  await prisma.workSession.deleteMany({});

  await prisma.workSession.create({
    data: {
      brigadistaId: brigadistaUser.id,
      brigadeId: brigade.id,
      status: SessionStatus.STARTED,
      startedAt: fechaHaceHoras(2),
      originDeviceId: mobileDevice1.id,
      lastModifiedByDeviceId: mobileDevice1.id,
    },
  });

  console.log('✅ Jornada de trabajo iniciada correctamente');
  console.log('🎉 Sembrado maestro dinámico completo y exitoso para MedicOS.');
}

main()
  .catch((e: unknown) => {
    console.error('❌ Error ejecutando el sembrado maestro:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });