// src/portals/authority/navigation/authority.navigation.ts
import {
  LayoutDashboard,
  TrendingUp,
  Activity,
  AlertTriangle,
  BellRing,
  Sparkles,
  Users,
  MapPin,
  Map,
  Flame,
  Target,
  Radio,
  History,
  LineChart,
  UserCheck,
  Package,
  Syringe,
  Shield,
  Baby,
  HeartPulse,
  CheckCircle2,
  Hospital,
  Building,
  Stethoscope,
  Boxes,
  Network,
  Lightbulb,
  BrainCircuit,
  AlertOctagon,
  FileText,
  FileBarChart,
  PieChart,
  Download,
  Sliders,
  Bell,
  Lock,
  FileOutput,
} from 'lucide-react';

export const AUTHORITY_NAVIGATION = [
  {
    title: 'DASHBOARD EJECUTIVO',
    items: [
      { name: 'Resumen General', path: '/autoridad/dashboard/resumen', icon: LayoutDashboard },
    ],
  },
  {
    title: 'VIGILANCIA EPIDEMIOLÓGICA',
    items: [
      { name: 'Tendencias Epidemiológicas', path: '/autoridad/vigilancia-epidemiologica/tendencias', icon: TrendingUp },
      { name: 'Monitoreo de Enfermedades', path: '/autoridad/vigilancia-epidemiologica/enfermedades', icon: Activity },
      { name: 'Factores de Riesgo', path: '/autoridad/vigilancia-epidemiologica/factores-riesgo', icon: AlertTriangle },
      { name: 'Alertas Sanitarias', path: '/autoridad/vigilancia-epidemiologica/alertas', icon: BellRing },
      { name: 'Predicciones IA', path: '/autoridad/vigilancia-epidemiologica/predicciones-ia', icon: Sparkles },
    ],
  },
  {
    title: 'COBERTURA SANITARIA',
    items: [
      { name: 'Comunidades', path: '/autoridad/cobertura-sanitaria/comunidades', icon: Users },
      { name: 'Municipios', path: '/autoridad/cobertura-sanitaria/municipios', icon: MapPin },
      { name: 'Departamentos', path: '/autoridad/cobertura-sanitaria/departamentos', icon: Map },
      { name: 'Mapas de Calor', path: '/autoridad/cobertura-sanitaria/mapas-calor', icon: Flame },
      { name: 'Sectores Prioritarios', path: '/autoridad/cobertura-sanitaria/sectores-prioritarios', icon: Target },
    ],
  },
  {
    title: 'GESTIÓN DE BRIGADAS',
    items: [
      { name: 'Brigadas Activas', path: '/autoridad/brigadas/activas', icon: Radio },
      { name: 'Historial de Brigadas', path: '/autoridad/brigadas/historial', icon: History },
      { name: 'Rendimiento y Métricas', path: '/autoridad/brigadas/rendimiento', icon: LineChart },
      { name: 'Personal Médico', path: '/autoridad/brigadas/personal-medico', icon: UserCheck },
      { name: 'Recursos Utilizados', path: '/autoridad/brigadas/recursos-utilizados', icon: Package },
    ],
  },
  {
    title: 'CAMPAÑAS DE SALUD',
    items: [
      { name: 'Vacunación', path: '/autoridad/campanas/vacunacion', icon: Syringe },
      { name: 'Prevención', path: '/autoridad/campanas/prevencion', icon: Shield },
      { name: 'Salud Materna', path: '/autoridad/campanas/salud-materna', icon: Baby },
      { name: 'Enfermedades Crónicas', path: '/autoridad/campanas/enfermedades-cronicas', icon: HeartPulse },
      { name: 'Resultados e Impacto', path: '/autoridad/campanas/resultados', icon: CheckCircle2 },
    ],
  },
  {
    title: 'RED DE ESTABLECIMIENTOS',
    items: [
      { name: 'Unidades de Salud', path: '/autoridad/establecimientos/unidades-salud', icon: Hospital },
      { name: 'Hospitales', path: '/autoridad/establecimientos/hospitales', icon: Building },
      { name: 'Clínicas', path: '/autoridad/establecimientos/clinicas', icon: Stethoscope },
      { name: 'Inventario Global', path: '/autoridad/establecimientos/inventario', icon: Boxes },
      { name: 'Cobertura de Red', path: '/autoridad/establecimientos/cobertura', icon: Network },
    ],
  },
  {
    title: 'INTELIGENCIA ARTIFICIAL',
    items: [
      { name: 'Resumen Ejecutivo IA', path: '/autoridad/inteligencia-artificial/resumen-ejecutivo', icon: Sparkles },
      { name: 'Recomendaciones Estratégicas', path: '/autoridad/inteligencia-artificial/recomendaciones', icon: Lightbulb },
      { name: 'Modelos Predictivos', path: '/autoridad/inteligencia-artificial/predicciones', icon: BrainCircuit },
      { name: 'Factores de Riesgo IA', path: '/autoridad/inteligencia-artificial/factores-riesgo', icon: AlertOctagon },
    ],
  },
  {
    title: 'REPORTES Y ANALÍTICA BI',
    items: [
      { name: 'Reportes Epidemiológicos', path: '/autoridad/reportes/epidemiologicos', icon: FileText },
      { name: 'Reportes de Brigadas', path: '/autoridad/reportes/brigadas', icon: FileBarChart },
      { name: 'Indicadores Sanitarios', path: '/autoridad/reportes/indicadores', icon: PieChart },
      { name: 'Exportaciones y Programados', path: '/autoridad/reportes/exportaciones', icon: Download },
    ],
  },
  {
    title: 'CONFIGURACIÓN',
    items: [
      { name: 'Preferencias', path: '/autoridad/configuracion/preferencias', icon: Sliders },
      { name: 'Notificaciones y Alertas', path: '/autoridad/configuracion/notificaciones', icon: Bell },
      { name: 'Permisos de Acceso', path: '/autoridad/configuracion/permisos', icon: Lock },
      { name: 'Exportación de Datos', path: '/autoridad/configuracion/exportacion', icon: FileOutput },
    ],
  },
];